def fstr(template, **kwargs):
    return eval(f"f'{template}'", kwargs)


template = [
    "set_property BEL D6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[1].gen_mux_j[0].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[1].gen_mux_j[0].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL C6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[1].gen_mux_j[1].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[1].gen_mux_j[1].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL B6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[1].gen_mux_j[2].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[1].gen_mux_j[2].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL A6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[1].gen_mux_j[3].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[1].gen_mux_j[3].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL D6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[2].gen_mux_j[0].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}Y{slice_y0} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[2].gen_mux_j[0].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL C6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[2].gen_mux_j[1].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}Y{slice_y0} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[2].gen_mux_j[1].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL B6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[2].gen_mux_j[2].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}Y{slice_y0} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[2].gen_mux_j[2].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL A6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[2].gen_mux_j[3].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}Y{slice_y0} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[2].gen_mux_j[3].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL D6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[3].gen_mux_j[0].gen_last_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[3].gen_mux_j[0].gen_last_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL C6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[3].gen_mux_j[1].gen_last_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[3].gen_mux_j[1].gen_last_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL B6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[3].gen_mux_j[2].gen_last_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[3].gen_mux_j[2].gen_last_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL A6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[3].gen_mux_j[3].gen_last_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_mux_i[3].gen_mux_j[3].gen_last_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL D6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_nand[0].nand_inst/lut6_inst}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_nand[0].nand_inst/lut6_inst}}]",
    "set_property BEL C6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_nand[1].nand_inst/lut6_inst}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_nand[1].nand_inst/lut6_inst}}]",
    "set_property BEL B6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_nand[2].nand_inst/lut6_inst}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_nand[2].nand_inst/lut6_inst}}]",
    "set_property BEL A6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_nand[3].nand_inst/lut6_inst}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/open_loop_mux_ro_inst/gen_nand[3].nand_inst/lut6_inst}}]",
    "set_property BEL D6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[0]_i_3}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[0]_i_3}}]",
    "set_property BEL C6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[0]_i_4}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[0]_i_4}}]",
    "set_property BEL B6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[0]_i_5}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[0]_i_5}}]",
    "set_property BEL A6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[0]_i_6}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[0]_i_6}}]",
    "set_property BEL D6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[0]_i_7}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[0]_i_7}}]",
    "set_property BEL C6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[0]_i_8}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[0]_i_8}}]",
    "set_property BEL B5LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[0]_i_9}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[0]_i_9}}]",
    "set_property BEL A5LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[8]_i_2}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[8]_i_2}}]",
    "set_property BEL D6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[8]_i_3}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[8]_i_3}}]",
    "set_property BEL C6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[12]_i_2}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[12]_i_2}}]",
    "set_property BEL B6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[12]_i_3}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[12]_i_3}}]",
    "set_property BEL A6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[16]_i_2}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[16]_i_2}}]",
    "set_property BEL D6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[16]_i_3}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[16]_i_3}}]",
    "set_property BEL C6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[20]_i_2}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[20]_i_2}}]",
    "set_property BEL B6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[20]_i_3}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[20]_i_3}}]",
    "set_property BEL A5LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[24]_i_2}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[24]_i_2}}]",
    "set_property BEL D6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[24]_i_3}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0 - 2} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[24]_i_3}}]",
    "set_property BEL C5LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[24]_i_4}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0 - 2} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[24]_i_4}}]",
    "set_property BEL B5LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[28]_i_2}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0 - 2} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[28]_i_2}}]",
    "set_property BEL A6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[28]_i_3}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0 - 2} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter[28]_i_3}}]",
    "set_property BEL D5FF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[0]}}]",
    "set_property LOC SLICE_X{slice_x0}{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[0]}}]",
    "set_property BEL C5FF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[1]}}]",
    "set_property LOC SLICE_X{slice_x0}{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[1]}}]",
    "set_property BEL CFF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[2]}}]",
    "set_property LOC SLICE_X{slice_x0}{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[2]}}]",
    "set_property BEL B5FF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[3]}}]",
    "set_property LOC SLICE_X{slice_x0}{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[3]}}]",
    "set_property BEL A5FF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[4]}}]",
    "set_property LOC SLICE_X{slice_x0}{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[4]}}]",
    "set_property BEL D5FF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[5]}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[5]}}]",
    "set_property BEL DFF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[6]}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[6]}}]",
    "set_property BEL CFF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[7]}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[7]}}]",
    "set_property BEL BFF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[8]}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[8]}}]",
    "set_property BEL AFF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[9]}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[9]}}]",
    "set_property BEL D5FF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[10]}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[10]}}]",
    "set_property BEL DFF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[11]}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[11]}}]",
    "set_property BEL C5FF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[12]}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[12]}}]",
    "set_property BEL CFF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[13]}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[13]}}]",
    "set_property BEL B5FF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[14]}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[14]}}]",
    "set_property BEL BFF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[15]}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[15]}}]",
    "set_property BEL A5FF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[16]}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[16]}}]",
    "set_property BEL AFF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[17]}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[17]}}]",
    "set_property BEL D5FF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[18]}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[18]}}]",
    "set_property BEL DFF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[19]}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[19]}}]",
    "set_property BEL C5FF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[20]}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[20]}}]",
    "set_property BEL CFF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[21]}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[21]}}]",
    "set_property BEL B5FF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[22]}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[22]}}]",
    "set_property BEL BFF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[23]}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[23]}}]",
    "set_property BEL AFF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[24]}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0 - 1} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[24]}}]",
    "set_property BEL D5FF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[25]}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0 - 2} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[25]}}]",
    "set_property BEL DFF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[26]}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0 - 2} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[26]}}]",
    "set_property BEL CFF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[27]}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0 - 2} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[27]}}]",
    "set_property BEL BFF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[28]}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0 - 2} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[28]}}]",
    "set_property BEL A5FF [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[29]}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0 - 2} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_counter_reg[29]}}]",
    "set_property BEL D6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_rst_cscnt_i_1}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}Y{slice_y0 - 2} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/async_ro_counter_inst/s_rst_cscnt_i_1}}]",
    "set_property BEL D6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/output_mux/mux}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 2} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/output_mux/mux}}]",
    "set_property BEL C5LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/output_mux/s_counter[0]_i_2}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 2} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_0/output_mux/s_counter[0]_i_2}}]",
    "set_property BEL D6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/output_mux/mux}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0 - 2} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/output_mux/mux}}]",
    "set_property BEL D6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[1].gen_mux_j[0].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0 - 3} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[1].gen_mux_j[0].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL C6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[1].gen_mux_j[1].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0 - 3} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[1].gen_mux_j[1].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL B6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[1].gen_mux_j[2].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0 - 3} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[1].gen_mux_j[2].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL A6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[1].gen_mux_j[3].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0}Y{slice_y0 - 3} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[1].gen_mux_j[3].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL D6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[2].gen_mux_j[0].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}Y{slice_y0 - 3} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[2].gen_mux_j[0].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL C6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[2].gen_mux_j[1].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}Y{slice_y0 - 3} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[2].gen_mux_j[1].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL B6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[2].gen_mux_j[2].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}Y{slice_y0 - 3} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[2].gen_mux_j[2].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL A6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[2].gen_mux_j[3].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0 - 1}Y{slice_y0 - 3} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[2].gen_mux_j[3].gen_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL D6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[3].gen_mux_j[0].gen_last_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 3} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[3].gen_mux_j[0].gen_last_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL C6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[3].gen_mux_j[1].gen_last_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 3} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[3].gen_mux_j[1].gen_last_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL B6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[3].gen_mux_j[2].gen_last_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 3} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[3].gen_mux_j[2].gen_last_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL A6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[3].gen_mux_j[3].gen_last_mux_row.lut_mux_inst/mux}}]",
    "set_property LOC SLICE_X{slice_x0 + 2}Y{slice_y0 - 3} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_mux_i[3].gen_mux_j[3].gen_last_mux_row.lut_mux_inst/mux}}]",
    "set_property BEL D6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_nand[0].nand_inst/lut6_inst}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0 - 3} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_nand[0].nand_inst/lut6_inst}}]",
    "set_property BEL C6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_nand[1].nand_inst/lut6_inst}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0 - 3} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_nand[1].nand_inst/lut6_inst}}]",
    "set_property BEL B6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_nand[2].nand_inst/lut6_inst}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0 - 3} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_nand[2].nand_inst/lut6_inst}}]",
    "set_property BEL A6LUT [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_nand[3].nand_inst/lut6_inst}}]",
    "set_property LOC SLICE_X{slice_x0 + 1}Y{slice_y0 - 3} [get_cells {{design_1_i/mux_ro_variance_0/U0/gen_ro[{i}].cscnt_ro_counter_inst/ro_inst_1/open_loop_mux_ro_inst/gen_nand[3].nand_inst/lut6_inst}}]",
]

slice_x0 = 27
slice_y0 = 148
# i, slice_x0, slice_y0
placement_list = [
    (0, 27, 148),
    (1, 43, 148),
    (2, 27, 115),
    (3, 43, 115),
    (4, 59, 148),
    (5, 85, 147),
    (6, 109, 147),
    (7, 63, 116),
    (8, 91, 113),
    (9, 109, 115),
    (10, 27, 98),
    (11, 43, 95),
    (12, 27, 65),
    (13, 43, 68),
    (14, 59, 99),
    (15, 91, 96),
    (16, 109, 97),
    (17, 59, 55),
    (18, 91, 62),
    (19, 109, 58),
    (20, 9, 49),
    (21, 21, 47),
    (22, 39, 48),
    (23, 3, 12),
    (24, 21, 9),
    (25, 43, 14),
    (26, 59, 46),
    (27, 91, 44),
    (28, 109, 46),
    (29, 59, 8),
    (30, 91, 7),
    (31, 109, 7),
]

with open("generated_placement.xdc", "w") as f:
    for placement in placement_list:
        result_list = [
            fstr(i, i=placement[0], slice_x0=placement[1], slice_y0=placement[2])
            for i in template
        ]
        f.write(f"\n\n# placement #{placement[0]}\n")
        f.write("\n".join(result_list))
